# Generated by Django 2.2.6 on 2020-02-22 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Module',
            new_name='Modules',
        ),
    ]
