# Generated by Django 2.2.6 on 2020-02-22 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200222_1450'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackBank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_bank', models.CharField(default='', max_length=500)),
                ('category', models.CharField(default='', max_length=10)),
            ],
        ),
        migrations.RenameModel(
            old_name='FeedbackGeneratedBank',
            new_name='FeedbackBankTwo',
        ),
        migrations.RenameModel(
            old_name='GradeAndMarks',
            new_name='Grade',
        ),
        migrations.RenameModel(
            old_name='Modules',
            new_name='Module',
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='module',
            field=models.CharField(default='None', max_length=20),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
