# Generated by Django 2.2.6 on 2020-02-25 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20200225_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedfeedback',
            name='created_by',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
