# Generated by Django 2.2.6 on 2020-03-05 15:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20200304_1740'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='correct_answers',
        ),
        migrations.RemoveField(
            model_name='test',
            name='incorrect_answers',
        ),
        migrations.AlterField(
            model_name='test',
            name='num_subquestions',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
