# Generated by Django 2.2.6 on 2020-03-12 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20200305_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='answersbank',
            name='weakest_topic',
            field=models.CharField(default='None', max_length=100000),
        ),
    ]
