# Generated by Django 2.2.6 on 2020-03-18 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_answersbank_weakest_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='answersbank',
            name='topics',
            field=models.CharField(default='None', max_length=100000),
        ),
    ]
