# Generated by Django 2.2.6 on 2020-03-21 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_answersbank_topics'),
    ]

    operations = [
        migrations.AddField(
            model_name='answersbank',
            name='topic_mark_breakdown',
            field=models.CharField(default='None', max_length=100000),
        ),
    ]
