# Generated by Django 2.2.6 on 2020-03-26 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_answersbank_topic_mark_breakdown'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImprovementFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_of_improvement', models.CharField(default='None', max_length=70)),
                ('improvement_feedback', models.CharField(default='None', max_length=10000)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Test')),
            ],
        ),
    ]
