# Generated by Django 2.2.6 on 2020-03-28 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_improvementfeedback'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacherprofile',
            old_name='module',
            new_name='avatar',
        ),
        migrations.RemoveField(
            model_name='teacherprofile',
            name='profile_pic',
        ),
        migrations.AddField(
            model_name='improvementfeedback',
            name='user',
            field=models.CharField(default='None', max_length=70),
        ),
    ]
