# Generated by Django 2.2.6 on 2020-04-05 19:24

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackBank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_bank', models.CharField(default='', max_length=500)),
                ('category', models.CharField(default='', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='FeedbackBankTwo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_bank', models.CharField(default='', max_length=100000)),
                ('category', models.CharField(default='', max_length=10)),
                ('percentage', models.IntegerField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(default='', max_length=50)),
                ('grade_mark', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('effectiveness', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('year_of_module', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)])),
                ('code', models.CharField(default='', max_length=50)),
                ('description', models.TextField()),
                ('num_students', models.IntegerField(default=0, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PreProcessedData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processed_feedback', models.CharField(default='None', max_length=100000)),
                ('rating', models.IntegerField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('test_count', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('num_subquestions', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('description', models.CharField(default='None', max_length=70)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('questiontype', models.CharField(default='None', max_length=50)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedbackapp.Module')),
            ],
            options={
                'verbose_name_plural': 'Tests',
                'ordering': ['created_date'],
            },
        ),
        migrations.CreateModel(
            name='UserTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='None', max_length=70)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedbackapp.Test')),
            ],
        ),
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(default='EECS', max_length=200)),
                ('user_type', models.CharField(default='teacher', max_length=200)),
                ('avatar', models.CharField(default='None', max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SavedFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default='None', max_length=70)),
                ('feedback', models.CharField(default='None', max_length=500)),
                ('percentage', models.IntegerField(default=0, null=True)),
                ('created_by', models.CharField(default='None', max_length=100)),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedbackapp.Grade')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedbackapp.Test')),
            ],
        ),
        migrations.CreateModel(
            name='ImprovementFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_of_improvement', models.CharField(default='None', max_length=70)),
                ('user', models.CharField(default='None', max_length=70)),
                ('improvement_feedback', models.CharField(default='None', max_length=10000)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedbackapp.Test')),
            ],
        ),
        migrations.AddField(
            model_name='grade',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedbackapp.Test'),
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.CharField(default='None', max_length=500)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedbackapp.Test')),
            ],
        ),
        migrations.CreateModel(
            name='AnswersBank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_mark_for_question', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('topics', models.CharField(default='None', max_length=100000)),
                ('total_sub_marks', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('topic_mark_breakdown', models.CharField(default='None', max_length=100000)),
                ('weakest_topic', models.CharField(default='None', max_length=100000)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedbackapp.Test')),
            ],
        ),
    ]
